### ISSUE TITLE
BUG: Squished Flow Run detail options if there are more than two

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/ui#1056]
**Bug Description**

![Screen Shot 2021-09-22 at 10 35 03 AM](https://user-images.githubusercontent.com/2325367/134368097-cbc9abc0-e94d-4fab-aca0-ddb51ea39e20.png)

**Steps To Reproduce**

1. Need a flow run with parameters and a run config

**Browsers Tested:**
* [X] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

**Comment by joeclayallday** [comment]
Proposed fix to this issue. We show these actions as proper tabs under their headers. Here's a mockup. This will grow the height of all blocks slightly. At really small widths, we might have to only show the icons instead of words.

![Tab-Change](https://user-images.githubusercontent.com/4295811/134981071-b2a7949b-a2b6-4d0d-9dd2-da716be0a852.jpg)

**Comment by whimsicallyson** [comment]
my only question/comment is how it works if there are more tab options than the width of the card. does it overflow properly in the horizontal, or do we wend up with the same issue that we had with the old implementation?
