### ISSUE TITLE
Placing Prefect UI behind proxy

### ISSUE THREAD

**Issue by oleksandr** [PrefectHQ/ui#109]
## Current behavior

Currently it's pretty much impossible to put Prefect UI container behind proxy and make it serve under "/some/other/path" but not root "/".

## Proposed behavior

It would be great to implement either of options:
 1. Pass env var (e.g. `PROXY_ADDRESS_FORWARDING`) that will respect all incoming `X-Forwarding-*` headers and adjust behaviour.
 2. Pass env var (e.g. `BASE_URL`) to communicate to the static app it's not in the root path.

**Comment by majikman111** [comment]
Is this features currently being implemented? I am using Prefect behind a reverse proxy and previously was able to create a custom docker image as described in PR #450. But as of version 2021-01-05 on-site builds are not possible due to embedded private keys. Now I cannot update the UI as I cannot serve it from behind a reverse proxy.

**Comment by dwissm1** [comment]
+1 desperately needed.

**Comment by igonro** [comment]
Hello @oleksandr @majikman111 @dwissm1 

Were you able to make it work behind a proxy? I am having some issues to make it work. Can you help me in [this discussion](https://github.com/PrefectHQ/prefect/discussions/5376)?

Thanks!

**Comment by TonyTromp** [comment]
+1

**Comment by igonro** [comment]
I know this isn't a suitable solution for all the scenarios, but someone may find this useful.

If you are coming to this issue because you have a Prefect on a server without GUI and you want to use Prefect UI, the easiest solution is to connect to the server using SSH port forwarding (remember to enable it for Prefect UI and Prefect Server), this way you can use Prefect UI from external PC.

Example:
1. Write something like this in the ssh config file.
```yaml
# ~/.ssh/config
Host prefect-port-forwarding
    HostName YOUR_SERVER_IP
    User YOUR_USER
    LocalForward 8080 localhost:8080
    LocalForward 4200 localhost:4200
```
2. Run `ssh prefect-port-forwarding`.
3. Open a tab in your browser and go to `http://localhost:8080`.
4. Set the `Prefect Server GraphQL endpoint` to `http://localhost:4200/graphql`.

And now you can use Prefect UI in your PC even if Prefect is in a server. 😄 

It's a pretty simple and maybe obvious solution, but we were going crazy trying to place Prefect UI behind Nginx, and this simple solution satisfied our needs.
