### ISSUE TITLE
BUG: Completed automation summaries do not reflect selected options

### ISSUE THREAD

**Issue by tpdorsey** [PrefectHQ/ui#1118]
**Bug Description**
After creating a new automation, the selected flow and state are not correctly shown in the summary of the flow, and clicking on the summary it's not clear that it captured my original selections.

**Steps To Reproduce**

1. Create a new automation
2. Click flow run, then Next
3. Click my flow ("festracker", it's the only one in my account), then Next
4. Click Changes State event, then Failed, then Next
5. Click "Alert Service" action (only one configured in my account)

The New Automation section at this point shows:

`When any run from festracker changes state to Failed, then Alert Service.`

After I click Save, the resulting item under Automations says:

`When any run from any flow changes to any of these states, then Alert Service.`

This doesn't reflect my choices. Further, if I click on the saved automation and click through the options...

1. The flow I selected is listed, but not selected. If I select it, festracker is added to the automation description as originally configured. (see attached screenshots)
2. The event Changes State is correctly selected, but the state itself is configured Custom:Failed rather than just the default Failed state on the first row.

I did not test whether the automation actually functioned as intended.

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

Screenshots 
![AutomationDetails](https://user-images.githubusercontent.com/370316/140817085-faa954fb-abe9-4029-95e9-350211c7dd9d.png)
![Flow not selected](https://user-images.githubusercontent.com/370316/140817088-ae0b7126-8848-4b49-8ad9-1b631dc9c2ca.png)
![Custom Rather than Failed](https://user-images.githubusercontent.com/370316/140817089-3cdd2642-8f93-43cd-ae04-3dcaf971acf6.png)

**Comment by zhen0** [comment]
Thanks for reporting this @tpdorsey - we have an option where a user can select to add an automation to all their flows.  You caught a bug where we presumed a user with only one flow wanted to include all their flows (as that matched the number of flows they had selected).  This should be fixed in #1129.

The states issue is actually a deliberate design - "Failed" also includes "Triggerfailed" and "TimedOut" which is why we use "any of these states" with the listed states on hover.  In Orion, we should consider whether there's a more user friendly/intuitive way to show that.
